---
abstract: 'embedding RDF in HTML the crazy way'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
  Test::RDF: 0.23
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - HTML
  - N-Triples
  - 'Notation 3'
  - RDF
  - RDF/JSON
  - RDF/XML
  - 'Semantic Web'
  - Turtle
  - XHTML
  - script
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Embedded::Turtle
name: HTML-Embedded-Turtle
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  Object::AUTHORITY: 0
  RDF::RDFa::Parser: 1.093
  RDF::TriN3: 0
  RDF::Trine: 0.135
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-Embedded-Turtle
  homepage: https://metacpan.org/release/HTML-Embedded-Turtle
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-html-embedded-turtle
version: 0.404
